// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using ReportingService.Domain.Enums;
using ReportingService.Infrastructure.Persistence;

#nullable disable

namespace ReportingService.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(ReportingDbContext))]
    partial class ReportingDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "export_status", new[] { "queued", "processing", "completed", "failed" });
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ReportingService.Domain.Entities.ExportJob", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("text")
                        .HasColumnName("error_message");

                    b.Property<DateTime>("RequestedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("requested_at");

                    b.Property<Guid>("RequestedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("requested_by");

                    b.Property<string>("ResultFileName")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("result_file_name");

                    b.Property<string>("ResultS3Key")
                        .HasColumnType("text")
                        .HasColumnName("result_s3_key");

                    b.Property<ExportStatus>("Status")
                        .HasColumnType("export_status")
                        .HasColumnName("status");

                    b.Property<Guid>("SubjectId")
                        .HasColumnType("uuid")
                        .HasColumnName("subject_id");

                    b.HasKey("Id");

                    b.HasIndex("Status")
                        .HasDatabaseName("idx_export_jobs_status");

                    b.HasIndex("SubjectId")
                        .HasDatabaseName("idx_export_jobs_subject");

                    b.ToTable("export_jobs", (string)null);
                });

            modelBuilder.Entity("ReportingService.Domain.Entities.MarkerProgress", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("AssignedCount")
                        .HasColumnType("integer")
                        .HasColumnName("assigned_count");

                    b.Property<decimal?>("AvgScore")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)")
                        .HasColumnName("avg_score");

                    b.Property<int>("CompletedCount")
                        .HasColumnType("integer")
                        .HasColumnName("completed_count");

                    b.Property<int>("DraftingCount")
                        .HasColumnType("integer")
                        .HasColumnName("drafting_count");

                    b.Property<DateTime?>("LastActivityAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_activity_at");

                    b.Property<Guid>("SubjectId")
                        .HasColumnType("uuid")
                        .HasColumnName("subject_id");

                    b.Property<Guid>("TeacherId")
                        .HasColumnType("uuid")
                        .HasColumnName("teacher_id");

                    b.Property<decimal?>("ThroughputPerHour")
                        .HasPrecision(6, 2)
                        .HasColumnType("numeric(6,2)")
                        .HasColumnName("throughput_per_hour");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("SubjectId")
                        .HasDatabaseName("idx_marker_progress_subj");

                    b.HasIndex("TeacherId")
                        .HasDatabaseName("idx_marker_progress_tea");

                    b.HasIndex("SubjectId", "TeacherId")
                        .IsUnique();

                    b.ToTable("marker_progress", (string)null);
                });

            modelBuilder.Entity("ReportingService.Domain.Entities.SubjectProgress", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("CompletedPapers")
                        .HasColumnType("integer")
                        .HasColumnName("completed_papers");

                    b.Property<DateTime?>("EstimatedFinish")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("estimated_finish");

                    b.Property<int>("InProgress")
                        .HasColumnType("integer")
                        .HasColumnName("in_progress");

                    b.Property<int>("NotStarted")
                        .HasColumnType("integer")
                        .HasColumnName("not_started");

                    b.Property<decimal?>("ScoreAvg")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)")
                        .HasColumnName("score_avg");

                    b.Property<decimal?>("ScoreMax")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)")
                        .HasColumnName("score_max");

                    b.Property<decimal?>("ScoreMin")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)")
                        .HasColumnName("score_min");

                    b.Property<Guid>("SubjectId")
                        .HasColumnType("uuid")
                        .HasColumnName("subject_id");

                    b.Property<int>("TotalPapers")
                        .HasColumnType("integer")
                        .HasColumnName("total_papers");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("SubjectId")
                        .IsUnique();

                    b.ToTable("subject_progress", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
