// <auto-generated />
using System;
using GradingService.Domain.Enums;
using GradingService.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace GradingService.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(GradingDbContext))]
    partial class GradingDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "ai_review_status", new[] { "pending", "accepted", "rejected", "modified" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "ai_sync_status", new[] { "not_requested", "queued", "processing", "completed", "failed" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "assignment_type", new[] { "first_grade", "cross_grade", "re_grade" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "grading_progress_status", new[] { "not_started", "drafting", "submitted" });
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("GradingService.Domain.Entities.AuditLog", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("action");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("EntityId")
                        .HasColumnType("uuid")
                        .HasColumnName("entity_id");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("entity_type");

                    b.Property<string>("NewValue")
                        .HasColumnType("jsonb")
                        .HasColumnName("new_value");

                    b.Property<string>("OldValue")
                        .HasColumnType("jsonb")
                        .HasColumnName("old_value");

                    b.Property<string>("Reason")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("reason");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .HasDatabaseName("idx_audit_user");

                    b.HasIndex("EntityType", "EntityId")
                        .HasDatabaseName("idx_audit_entity");

                    b.ToTable("audit_logs", (string)null);
                });

            modelBuilder.Entity("GradingService.Domain.Entities.GradingAssignment", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<AiSyncStatus>("AiStatus")
                        .HasColumnType("ai_sync_status")
                        .HasColumnName("ai_status");

                    b.Property<AssignmentType>("AssignmentType")
                        .HasColumnType("assignment_type")
                        .HasColumnName("assignment_type");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<bool>("IsFlagged")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_flagged");

                    b.Property<GradingProgressStatus>("Status")
                        .HasColumnType("grading_progress_status")
                        .HasColumnName("status");

                    b.Property<Guid>("StudentPaperId")
                        .HasColumnType("uuid")
                        .HasColumnName("student_paper_id");

                    b.Property<Guid>("SubjectId")
                        .HasColumnType("uuid")
                        .HasColumnName("subject_id");

                    b.Property<Guid>("TeacherId")
                        .HasColumnType("uuid")
                        .HasColumnName("teacher_id");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("AiStatus")
                        .HasDatabaseName("idx_assign_ai_status");

                    b.HasIndex("IsFlagged")
                        .HasDatabaseName("idx_assign_flagged");

                    b.HasIndex("Status")
                        .HasDatabaseName("idx_assign_status");

                    b.HasIndex("StudentPaperId")
                        .HasDatabaseName("idx_assign_paper");

                    b.HasIndex("SubjectId")
                        .HasDatabaseName("idx_assign_subject");

                    b.HasIndex("TeacherId")
                        .HasDatabaseName("idx_assign_teacher");

                    b.HasIndex("StudentPaperId", "TeacherId", "AssignmentType")
                        .IsUnique();

                    b.ToTable("grading_assignments", (string)null);
                });

            modelBuilder.Entity("GradingService.Domain.Entities.GradingForm", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("ActiveSecondsSpent")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("active_seconds_spent");

                    b.Property<string>("AiPaperComment")
                        .HasColumnType("text")
                        .HasColumnName("ai_paper_comment");

                    b.Property<string>("AiSuggestionsJson")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("[]")
                        .HasColumnName("ai_suggestions_json");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("GeneralComment")
                        .HasColumnType("text")
                        .HasColumnName("general_comment");

                    b.Property<Guid>("GradingAssignmentId")
                        .HasColumnType("uuid")
                        .HasColumnName("grading_assignment_id");

                    b.Property<string>("InternalComment")
                        .HasColumnType("text")
                        .HasColumnName("internal_comment");

                    b.Property<DateTime?>("LastActiveAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_active_at");

                    b.Property<string>("PaperComment")
                        .HasColumnType("text")
                        .HasColumnName("paper_comment");

                    b.Property<int>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("row_version");

                    b.Property<DateTime?>("SubmittedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("submitted_at");

                    b.Property<decimal>("TotalScore")
                        .HasColumnType("numeric(5,2)")
                        .HasColumnName("total_score");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("GradingAssignmentId")
                        .IsUnique();

                    b.ToTable("grading_forms", (string)null);
                });

            modelBuilder.Entity("GradingService.Domain.Entities.GradingResumePointer", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AssignmentId")
                        .HasColumnType("uuid")
                        .HasColumnName("assignment_id");

                    b.Property<Guid>("BatchId")
                        .HasColumnType("uuid")
                        .HasColumnName("batch_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("TeacherId")
                        .HasColumnType("uuid")
                        .HasColumnName("teacher_id");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("TeacherId", "BatchId")
                        .IsUnique()
                        .HasDatabaseName("IX_grading_resume_pointers_teacher_id_batch_id");

                    b.ToTable("grading_resume_pointers", (string)null);
                });

            modelBuilder.Entity("GradingService.Domain.Entities.LecturerMarkerCodeView", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<string>("FullName")
                        .HasColumnType("text")
                        .HasColumnName("full_name");

                    b.Property<string>("MarkerCode")
                        .HasColumnType("text")
                        .HasColumnName("marker_code");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("UserId");

                    b.ToTable("lecturer_marker_code_view", (string)null);
                });

            modelBuilder.Entity("GradingService.Domain.Entities.MarkerAssignment", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("AliasEnd")
                        .HasColumnType("integer")
                        .HasColumnName("alias_end");

                    b.Property<int>("AliasStart")
                        .HasColumnType("integer")
                        .HasColumnName("alias_start");

                    b.Property<Guid?>("BatchId")
                        .HasColumnType("uuid")
                        .HasColumnName("batch_id");

                    b.Property<DateTime>("AssignedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("assigned_at");

                    b.Property<Guid>("AssignedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("assigned_by");

                    b.Property<Guid>("SubjectId")
                        .HasColumnType("uuid")
                        .HasColumnName("subject_id");

                    b.Property<Guid>("TeacherId")
                        .HasColumnType("uuid")
                        .HasColumnName("teacher_id");

                    b.Property<string>("ZipFileName")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("zip_file_name");

                    b.HasKey("Id");

                    b.HasIndex("SubjectId")
                        .HasDatabaseName("idx_marker_assign_subject");

                    b.HasIndex("TeacherId")
                        .HasDatabaseName("idx_marker_assign_teacher");

                    b.HasIndex("SubjectId", "AliasStart", "AliasEnd")
                        .IsUnique();

                    b.HasIndex("SubjectId", "BatchId")
                        .IsUnique()
                        .HasFilter("batch_id IS NOT NULL");

                    b.ToTable("marker_assignments", null, t =>
                        {
                            t.HasCheckConstraint("CK_marker_assignments_alias_end", "alias_end >= alias_start");

                            t.HasCheckConstraint("CK_marker_assignments_alias_start", "alias_start >= 1");
                        });
                });

            modelBuilder.Entity("GradingService.Domain.Entities.QuestionGradeDetail", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("AiDrafted")
                        .HasColumnType("boolean")
                        .HasColumnName("ai_drafted");

                    b.Property<AiReviewStatus>("AiReviewStatus")
                        .HasColumnType("ai_review_status")
                        .HasColumnName("ai_review_status");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("GradingFormId")
                        .HasColumnType("uuid")
                        .HasColumnName("grading_form_id");

                    b.Property<string>("GroupLabel")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("group_label");

                    b.Property<string>("Label")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("label");

                    b.Property<decimal>("MaxScore")
                        .HasColumnType("numeric(5,2)")
                        .HasColumnName("max_score");

                    b.Property<int>("OrderIndex")
                        .HasColumnType("integer")
                        .HasColumnName("order_index");

                    b.Property<string>("QuestionComment")
                        .HasColumnType("text")
                        .HasColumnName("question_comment");

                    b.Property<string>("QuestionNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("question_number");

                    b.Property<decimal>("Score")
                        .HasColumnType("numeric(5,2)")
                        .HasColumnName("score");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("GradingFormId")
                        .HasDatabaseName("idx_grade_details_form");

                    b.HasIndex("GradingFormId", "QuestionNumber")
                        .IsUnique();

                    b.ToTable("question_grade_details", null, t =>
                        {
                            t.HasCheckConstraint("CK_question_grade_details_score_range", "score >= 0 AND score <= max_score");
                        });
                });

            modelBuilder.Entity("MassTransit.EntityFrameworkCoreIntegration.InboxState", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime?>("Consumed")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("ConsumerId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("Delivered")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("ExpirationTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long?>("LastSequenceNumber")
                        .HasColumnType("bigint");

                    b.Property<Guid>("LockId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("MessageId")
                        .HasColumnType("uuid");

                    b.Property<int>("ReceiveCount")
                        .HasColumnType("integer");

                    b.Property<DateTime>("Received")
                        .HasColumnType("timestamp with time zone");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("bytea");

                    b.HasKey("Id");

                    b.HasIndex("Delivered");

                    b.ToTable("InboxState");
                });

            modelBuilder.Entity("MassTransit.EntityFrameworkCoreIntegration.OutboxMessage", b =>
                {
                    b.Property<long>("SequenceNumber")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("SequenceNumber"));

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<Guid?>("ConversationId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("CorrelationId")
                        .HasColumnType("uuid");

                    b.Property<string>("DestinationAddress")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<DateTime?>("EnqueueTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("ExpirationTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FaultAddress")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("Headers")
                        .HasColumnType("text");

                    b.Property<Guid?>("InboxConsumerId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("InboxMessageId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("InitiatorId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("MessageId")
                        .HasColumnType("uuid");

                    b.Property<string>("MessageType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("OutboxId")
                        .HasColumnType("uuid");

                    b.Property<string>("Properties")
                        .HasColumnType("text");

                    b.Property<Guid?>("RequestId")
                        .HasColumnType("uuid");

                    b.Property<string>("ResponseAddress")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<DateTime>("SentTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("SourceAddress")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("SequenceNumber");

                    b.HasIndex("EnqueueTime");

                    b.HasIndex("ExpirationTime");

                    b.HasIndex("OutboxId", "SequenceNumber")
                        .IsUnique();

                    b.HasIndex("InboxMessageId", "InboxConsumerId", "SequenceNumber")
                        .IsUnique();

                    b.ToTable("OutboxMessage");
                });

            modelBuilder.Entity("MassTransit.EntityFrameworkCoreIntegration.OutboxState", b =>
                {
                    b.Property<Guid>("OutboxId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("Created")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("Delivered")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long?>("LastSequenceNumber")
                        .HasColumnType("bigint");

                    b.Property<Guid>("LockId")
                        .HasColumnType("uuid");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("bytea");

                    b.HasKey("OutboxId");

                    b.HasIndex("Created");

                    b.ToTable("OutboxState");
                });

            modelBuilder.Entity("GradingService.Domain.Entities.GradingForm", b =>
                {
                    b.HasOne("GradingService.Domain.Entities.GradingAssignment", "GradingAssignment")
                        .WithOne("GradingForm")
                        .HasForeignKey("GradingService.Domain.Entities.GradingForm", "GradingAssignmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GradingAssignment");
                });

            modelBuilder.Entity("GradingService.Domain.Entities.QuestionGradeDetail", b =>
                {
                    b.HasOne("GradingService.Domain.Entities.GradingForm", "GradingForm")
                        .WithMany("QuestionGradeDetails")
                        .HasForeignKey("GradingFormId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GradingForm");
                });

            modelBuilder.Entity("MassTransit.EntityFrameworkCoreIntegration.OutboxMessage", b =>
                {
                    b.HasOne("MassTransit.EntityFrameworkCoreIntegration.OutboxState", null)
                        .WithMany()
                        .HasForeignKey("OutboxId");

                    b.HasOne("MassTransit.EntityFrameworkCoreIntegration.InboxState", null)
                        .WithMany()
                        .HasForeignKey("InboxMessageId", "InboxConsumerId")
                        .HasPrincipalKey("MessageId", "ConsumerId");
                });

            modelBuilder.Entity("GradingService.Domain.Entities.GradingAssignment", b =>
                {
                    b.Navigation("GradingForm");
                });

            modelBuilder.Entity("GradingService.Domain.Entities.GradingForm", b =>
                {
                    b.Navigation("QuestionGradeDetails");
                });
#pragma warning restore 612, 618
        }
    }
}
