// <auto-generated />
using System;
using GradingService.Domain.Enums;
using GradingService.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace GradingService.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(GradingDbContext))]
    partial class GradingDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "ai_review_status", new[] { "pending", "accepted", "rejected", "modified" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "ai_sync_status", new[] { "not_requested", "queued", "processing", "completed", "failed" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "assignment_type", new[] { "first_grade", "cross_grade", "re_grade" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "grading_progress_status", new[] { "not_started", "drafting", "submitted" });
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("GradingService.Domain.Entities.AuditLog", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("action");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("EntityId")
                        .HasColumnType("uuid")
                        .HasColumnName("entity_id");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("entity_type");

                    b.Property<string>("NewValue")
                        .HasColumnType("jsonb")
                        .HasColumnName("new_value");

                    b.Property<string>("OldValue")
                        .HasColumnType("jsonb")
                        .HasColumnName("old_value");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .HasDatabaseName("idx_audit_user");

                    b.HasIndex("EntityType", "EntityId")
                        .HasDatabaseName("idx_audit_entity");

                    b.ToTable("audit_logs", (string)null);
                });

            modelBuilder.Entity("GradingService.Domain.Entities.GradingAssignment", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<AiSyncStatus>("AiStatus")
                        .HasColumnType("ai_sync_status")
                        .HasColumnName("ai_status");

                    b.Property<AssignmentType>("AssignmentType")
                        .HasColumnType("assignment_type")
                        .HasColumnName("assignment_type");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<GradingProgressStatus>("Status")
                        .HasColumnType("grading_progress_status")
                        .HasColumnName("status");

                    b.Property<Guid>("StudentPaperId")
                        .HasColumnType("uuid")
                        .HasColumnName("student_paper_id");

                    b.Property<Guid>("SubjectId")
                        .HasColumnType("uuid")
                        .HasColumnName("subject_id");

                    b.Property<Guid>("TeacherId")
                        .HasColumnType("uuid")
                        .HasColumnName("teacher_id");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("AiStatus")
                        .HasDatabaseName("idx_assign_ai_status");

                    b.HasIndex("Status")
                        .HasDatabaseName("idx_assign_status");

                    b.HasIndex("StudentPaperId")
                        .HasDatabaseName("idx_assign_paper");

                    b.HasIndex("SubjectId")
                        .HasDatabaseName("idx_assign_subject");

                    b.HasIndex("TeacherId")
                        .HasDatabaseName("idx_assign_teacher");

                    b.HasIndex("StudentPaperId", "TeacherId", "AssignmentType")
                        .IsUnique();

                    b.ToTable("grading_assignments", (string)null);
                });

            modelBuilder.Entity("GradingService.Domain.Entities.GradingForm", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("GeneralComment")
                        .HasColumnType("text")
                        .HasColumnName("general_comment");

                    b.Property<Guid>("GradingAssignmentId")
                        .HasColumnType("uuid")
                        .HasColumnName("grading_assignment_id");

                    b.Property<string>("InternalComment")
                        .HasColumnType("text")
                        .HasColumnName("internal_comment");

                    b.Property<string>("PaperComment")
                        .HasColumnType("text")
                        .HasColumnName("paper_comment");

                    b.Property<int>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("row_version");

                    b.Property<DateTime?>("SubmittedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("submitted_at");

                    b.Property<decimal>("TotalScore")
                        .HasColumnType("numeric(5,2)")
                        .HasColumnName("total_score");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("GradingAssignmentId")
                        .IsUnique();

                    b.ToTable("grading_forms", (string)null);
                });

            modelBuilder.Entity("GradingService.Domain.Entities.MarkerAssignment", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("AliasEnd")
                        .HasColumnType("integer")
                        .HasColumnName("alias_end");

                    b.Property<int>("AliasStart")
                        .HasColumnType("integer")
                        .HasColumnName("alias_start");

                    b.Property<DateTime>("AssignedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("assigned_at");

                    b.Property<Guid>("AssignedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("assigned_by");

                    b.Property<Guid>("SubjectId")
                        .HasColumnType("uuid")
                        .HasColumnName("subject_id");

                    b.Property<Guid>("TeacherId")
                        .HasColumnType("uuid")
                        .HasColumnName("teacher_id");

                    b.HasKey("Id");

                    b.HasIndex("SubjectId")
                        .HasDatabaseName("idx_marker_assign_subject");

                    b.HasIndex("TeacherId")
                        .HasDatabaseName("idx_marker_assign_teacher");

                    b.HasIndex("SubjectId", "AliasStart", "AliasEnd")
                        .IsUnique();

                    b.ToTable("marker_assignments", null, t =>
                        {
                            t.HasCheckConstraint("CK_marker_assignments_alias_end", "alias_end >= alias_start");

                            t.HasCheckConstraint("CK_marker_assignments_alias_start", "alias_start >= 1");
                        });
                });

            modelBuilder.Entity("GradingService.Domain.Entities.QuestionGradeDetail", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("AiDrafted")
                        .HasColumnType("boolean")
                        .HasColumnName("ai_drafted");

                    b.Property<AiReviewStatus>("AiReviewStatus")
                        .HasColumnType("ai_review_status")
                        .HasColumnName("ai_review_status");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("GradingFormId")
                        .HasColumnType("uuid")
                        .HasColumnName("grading_form_id");

                    b.Property<decimal>("MaxScore")
                        .HasColumnType("numeric(5,2)")
                        .HasColumnName("max_score");

                    b.Property<string>("QuestionComment")
                        .HasColumnType("text")
                        .HasColumnName("question_comment");

                    b.Property<string>("QuestionNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("question_number");

                    b.Property<decimal>("Score")
                        .HasColumnType("numeric(5,2)")
                        .HasColumnName("score");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("GradingFormId")
                        .HasDatabaseName("idx_grade_details_form");

                    b.HasIndex("GradingFormId", "QuestionNumber")
                        .IsUnique();

                    b.ToTable("question_grade_details", null, t =>
                        {
                            t.HasCheckConstraint("CK_question_grade_details_score_range", "score >= 0 AND score <= max_score");
                        });
                });

            modelBuilder.Entity("GradingService.Domain.Entities.GradingForm", b =>
                {
                    b.HasOne("GradingService.Domain.Entities.GradingAssignment", "GradingAssignment")
                        .WithOne("GradingForm")
                        .HasForeignKey("GradingService.Domain.Entities.GradingForm", "GradingAssignmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GradingAssignment");
                });

            modelBuilder.Entity("GradingService.Domain.Entities.QuestionGradeDetail", b =>
                {
                    b.HasOne("GradingService.Domain.Entities.GradingForm", "GradingForm")
                        .WithMany("QuestionGradeDetails")
                        .HasForeignKey("GradingFormId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GradingForm");
                });

            modelBuilder.Entity("GradingService.Domain.Entities.GradingAssignment", b =>
                {
                    b.Navigation("GradingForm");
                });

            modelBuilder.Entity("GradingService.Domain.Entities.GradingForm", b =>
                {
                    b.Navigation("QuestionGradeDetails");
                });
#pragma warning restore 612, 618
        }
    }
}
