// <auto-generated />
using System;
using ExamCatalogService.Domain.Enums;
using ExamCatalogService.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace ExamCatalogService.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(ExamCatalogDbContext))]
    [Migration("20260618043351_InitialExamCatalogSchema")]
    partial class InitialExamCatalogSchema
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "exam_type", new[] { "FE", "PE", "PT", "OTHER" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "subject_status", new[] { "draft", "open", "grading", "closed" });
            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "pgcrypto");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ExamCatalogService.Domain.Entities.Exam", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateOnly?>("EndDate")
                        .HasColumnType("date")
                        .HasColumnName("end_date");

                    b.Property<ExamType>("ExamType")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("exam_type")
                        .HasDefaultValue(ExamType.FE)
                        .HasColumnName("exam_type");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("name");

                    b.Property<Guid>("SemesterId")
                        .HasColumnType("uuid")
                        .HasColumnName("semester_id");

                    b.Property<DateOnly?>("StartDate")
                        .HasColumnType("date")
                        .HasColumnName("start_date");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("SemesterId")
                        .HasDatabaseName("idx_exams_semester");

                    b.ToTable("exams", (string)null);
                });

            modelBuilder.Entity("ExamCatalogService.Domain.Entities.Question", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Label")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("label");

                    b.Property<decimal>("MaxScore")
                        .HasColumnType("numeric(5,2)")
                        .HasColumnName("max_score");

                    b.Property<int>("OrderIndex")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("order_index");

                    b.Property<string>("QuestionNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("question_number");

                    b.Property<Guid>("SubjectId")
                        .HasColumnType("uuid")
                        .HasColumnName("subject_id");

                    b.HasKey("Id");

                    b.HasIndex("SubjectId")
                        .HasDatabaseName("idx_questions_subject");

                    b.HasIndex("SubjectId", "QuestionNumber")
                        .IsUnique();

                    b.ToTable("questions", null, t =>
                        {
                            t.HasCheckConstraint("CK_questions_max_score", "max_score > 0");
                        });
                });

            modelBuilder.Entity("ExamCatalogService.Domain.Entities.Semester", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("code");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<DateOnly>("EndDate")
                        .HasColumnType("date")
                        .HasColumnName("end_date");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("date")
                        .HasColumnName("start_date");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("semesters", null, t =>
                        {
                            t.HasCheckConstraint("chk_semester_dates", "end_date > start_date");
                        });
                });

            modelBuilder.Entity("ExamCatalogService.Domain.Entities.Subject", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("ExamId")
                        .HasColumnType("uuid")
                        .HasColumnName("exam_id");

                    b.Property<string>("ExamPaperContentType")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("exam_paper_content_type");

                    b.Property<string>("ExamPaperFileName")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("exam_paper_file_name");

                    b.Property<string>("ExamPaperS3Key")
                        .HasColumnType("text")
                        .HasColumnName("exam_paper_s3_key");

                    b.Property<decimal>("MaxScore")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("numeric(5,2)")
                        .HasDefaultValue(10m)
                        .HasColumnName("max_score");

                    b.Property<string>("RubricContentType")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("rubric_content_type");

                    b.Property<string>("RubricFileName")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("rubric_file_name");

                    b.Property<string>("RubricS3Key")
                        .HasColumnType("text")
                        .HasColumnName("rubric_s3_key");

                    b.Property<int>("RubricVersion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1)
                        .HasColumnName("rubric_version");

                    b.Property<SubjectStatus>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("subject_status")
                        .HasDefaultValue(SubjectStatus.Draft)
                        .HasColumnName("status");

                    b.Property<string>("SubjectCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("subject_code");

                    b.Property<string>("Title")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("title");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("ExamId")
                        .HasDatabaseName("idx_subjects_exam");

                    b.HasIndex("Status")
                        .HasDatabaseName("idx_subjects_status");

                    b.HasIndex("ExamId", "SubjectCode")
                        .IsUnique();

                    b.ToTable("subjects", null, t =>
                        {
                            t.HasCheckConstraint("CK_subjects_max_score", "max_score > 0");
                        });
                });

            modelBuilder.Entity("ExamCatalogService.Domain.Entities.Exam", b =>
                {
                    b.HasOne("ExamCatalogService.Domain.Entities.Semester", "Semester")
                        .WithMany("Exams")
                        .HasForeignKey("SemesterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Semester");
                });

            modelBuilder.Entity("ExamCatalogService.Domain.Entities.Question", b =>
                {
                    b.HasOne("ExamCatalogService.Domain.Entities.Subject", "Subject")
                        .WithMany("Questions")
                        .HasForeignKey("SubjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Subject");
                });

            modelBuilder.Entity("ExamCatalogService.Domain.Entities.Subject", b =>
                {
                    b.HasOne("ExamCatalogService.Domain.Entities.Exam", "Exam")
                        .WithMany("Subjects")
                        .HasForeignKey("ExamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Exam");
                });

            modelBuilder.Entity("ExamCatalogService.Domain.Entities.Exam", b =>
                {
                    b.Navigation("Subjects");
                });

            modelBuilder.Entity("ExamCatalogService.Domain.Entities.Semester", b =>
                {
                    b.Navigation("Exams");
                });

            modelBuilder.Entity("ExamCatalogService.Domain.Entities.Subject", b =>
                {
                    b.Navigation("Questions");
                });
#pragma warning restore 612, 618
        }
    }
}
